name: Release

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+*"]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CARGO_TERM_COLOR: always

jobs:
  windows:
    runs-on: windows-latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: cargo test --release
      - name: Build
        run: cargo build --release
      - name: Upload portable executable
        run: |
          cp ./target/release/alacritty.exe ./Alacritty-${GITHUB_REF##*/}-portable.exe
          ./.github/workflows/upload_asset.sh \
            ./Alacritty-${GITHUB_REF##*/}-portable.exe $GITHUB_TOKEN
      - name: Install WiX
        run: dotnet tool install --global wix --version 4.0.5
      - name: Create msi installer
        run: |
          wix extension add WixToolset.UI.wixext/4.0.5 WixToolset.Util.wixext/4.0.5
          wix build -arch "x64" -ext WixToolset.UI.wixext -ext WixToolset.Util.wixext \
          -out "./Alacritty-${GITHUB_REF##*/}-installer.msi" "alacritty/windows/wix/alacritty.wxs"
      - name: Upload msi installer
        run: |
          ./.github/workflows/upload_asset.sh \
            ./Alacritty-${GITHUB_REF##*/}-installer.msi $GITHUB_TOKEN